# Hotel Booking Data Preparation & Quality Analysis

### SWYNEX Technologies — Data Science Internship | Task 1

## 1. Project Overview

This project focuses on preparing a public hotel booking dataset
for downstream data science and machine learning tasks.

The dataset contains hotel booking records from a resort hotel
and a city hotel. The data includes information about booking
characteristics, customer details, stay duration, room types,
distribution channels, cancellation status, and other booking
attributes.

### Objective

The primary objective of this task is to assess and improve the
quality of the dataset by:

- Understanding the dataset structure
- Identifying missing values
- Detecting duplicate records
- Validating data types
- Identifying inconsistent or invalid values
- Standardizing relevant fields
- Creating useful derived features
- Validating the final prepared dataset
- Documenting data preparation assumptions

The cleaned dataset will serve as the foundation for subsequent
exploratory data analysis and machine learning tasks.

## 2. Dataset Source

### Dataset

**Hotel Booking Demand**

The dataset contains hotel booking information from two hotels:
a resort hotel and a city hotel.

### Original Publication

Antonio, N., de Almeida, A., & Nunes, L. (2019).  
*Hotel booking demand datasets.*

**Reference:** Data in Brief, 22, 41–49  
**DOI:** 10.1016/j.dib.2018.11.126

### Source

The dataset is publicly available and is used here for
educational and data-science purposes.

### Data Preparation Note

The original dataset is preserved as the raw input. Cleaning
operations are performed on a working copy so that the original
data remains unchanged.

## 3. Import Libraries

The following Python libraries are used for data loading,
data manipulation, numerical analysis, and visualization.

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries imported successfully.")

Libraries imported successfully.

## 4. Load Dataset

The raw CSV file is loaded into a Pandas DataFrame.

The raw dataset will be preserved, while all preparation
operations will be performed on a separate working copy.

In [11]:
df_raw = pd.read_csv("hotel_bookings.csv")

df = df_raw.copy()

print("Dataset loaded successfully.")

Dataset loaded successfully.

In [12]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

## 5. Initial Data Inspection

Before modifying the dataset, an initial inspection is performed
to understand its dimensions, structure, data types, and
statistical characteristics.

This provides a baseline against which the final prepared
dataset can be compared.

In [14]:
df.shape

(119390, 32)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [17]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [18]:
df.tail()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
119385,City Hotel,0,23,2017,August,35,30,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [19]:
df.sample(5, random_state=42)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
30946,Resort Hotel,0,203,2016,December,49,2,2,5,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,F,F,4,No Deposit,250.0,NaN,0,Transient,66.8,0,0,Check-Out,2016-12-09
40207,City Hotel,1,82,2015,July,29,16,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,NaN,0,Transient,76.5,0,0,Canceled,2015-07-16
103708,City Hotel,0,25,2016,December,53,27,0,3,3,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,K,2,No Deposit,220.0,NaN,0,Transient-Party,60.0,0,1,Check-Out,2016-12-30
85144,City Hotel,0,1,2016,March,11,9,0,1,1,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,NaN,0,Transient-Party,95.0,0,0,Check-Out,2016-03-10
109991,City Hotel,0,70,2017,April,16,16,2,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,NaN,0,Transient,108.0,0,0,Check-Out,2017-04-20

In [20]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
is_canceled,119390.0,0.370416,0.482918,0.00,0.00,0.000,1.0,1.0
lead_time,119390.0,104.011416,106.863097,0.00,18.00,69.000,160.0,737.0
arrival_date_year,119390.0,2016.156554,0.707476,2015.00,2016.00,2016.000,2017.0,2017.0
arrival_date_week_number,119390.0,27.165173,13.605138,1.00,16.00,28.000,38.0,53.0
arrival_date_day_of_month,119390.0,15.798241,8.780829,1.00,8.00,16.000,23.0,31.0
stays_in_weekend_nights,119390.0,0.927599,0.998613,0.00,0.00,1.000,2.0,19.0
stays_in_week_nights,119390.0,2.500302,1.908286,0.00,1.00,2.000,3.0,50.0
adults,119390.0,1.856403,0.579261,0.00,2.00,2.000,2.0,55.0
children,119386.0,0.103890,0.398561,0.00,0.00,0.000,0.0,10.0
babies,119390.0,0.007949,0.097436,0.00,0.00,0.000,0.0,10.0
is_repeated_guest,119390.0,0.031912,0.175767,0.00,0.00,0.000,0.0,1.0
previous_cancellations,119390.0,0.087118,0.844336,0.00,0.00,0.000,0.0,26.0
previous_bookings_not_canceled,119390.0,0.137097,1.497437,0.00,0.00,0.000,0.0,72.0
booking_changes,119390.0,0.221124,0.652306,0.00,0.00,0.000,0.0,21.0
agent,103050.0,86.693382,110.774548,1.00,9.00,14.000,229.0,535.0
company,6797.0,189.266735,131.655015,6.00,62.00,179.000,270.0,543.0
days_in_waiting_list,119390.0,2.321149,17.594721,0.00,0.00,0.000,0.0,391.0
adr,119390.0,101.831122,50.535790,-6.38,69.29,94.575,126.0,5400.0
required_car_parking_spaces,119390.0,0.062518,0.245291,0.00,0.00,0.000,0.0,8.0
total_of_special_requests,119390.0,0.571363,0.792798,0.00,0.00,0.000,1.0,5.0

## 6. Data Quality Assessment

A column-level data quality assessment is performed to identify
missing values, data types, unique values, and potential issues
before applying any transformations.

In [21]:
quality_report = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.astype(str).values,
    "Missing_Count": df.isna().sum().values,
    "Missing_Percentage": (df.isna().mean() * 100).round(2).values,
    "Unique_Values": df.nunique(dropna=False).values
})

quality_report

,Column,Data_Type,Missing_Count,Missing_Percentage,Unique_Values
0,hotel,object,0,0.00,2
1,is_canceled,int64,0,0.00,2
2,lead_time,int64,0,0.00,479
3,arrival_date_year,int64,0,0.00,3
4,arrival_date_month,object,0,0.00,12
5,arrival_date_week_number,int64,0,0.00,53
6,arrival_date_day_of_month,int64,0,0.00,31
7,stays_in_weekend_nights,int64,0,0.00,17
8,stays_in_week_nights,int64,0,0.00,35
9,adults,int64,0,0.00,14
10,children,float64,4,0.00,6
11,babies,int64,0,0.00,5
12,meal,object,0,0.00,5
13,country,object,488,0.41,178
14,market_segment,object,0,0.00,8
15,distribution_channel,object,0,0.00,5
16,is_repeated_guest,int64,0,0.00,2
17,previous_cancellations,int64,0,0.00,15
18,previous_bookings_not_canceled,int64,0,0.00,73
19,reserved_room_type,object,0,0.00,10
20,assigned_room_type,object,0,0.00,12
21,booking_changes,int64,0,0.00,21
22,deposit_type,object,0,0.00,3
23,agent,float64,16340,13.69,334
24,company,float64,112593,94.31,353
25,days_in_waiting_list,int64,0,0.00,128
26,customer_type,object,0,0.00,4
27,adr,float64,0,0.00,8879
28,required_car_parking_spaces,int64,0,0.00,5
29,total_of_special_requests,int64,0,0.00,6
30,reservation_status,object,0,0.00,3
31,reservation_status_date,object,0,0.00,926

In [22]:
quality_report.sort_values(
    by="Missing_Percentage",
    ascending=False
)

,Column,Data_Type,Missing_Count,Missing_Percentage,Unique_Values
24,company,float64,112593,94.31,353
23,agent,float64,16340,13.69,334
13,country,object,488,0.41,178
0,hotel,object,0,0.00,2
4,arrival_date_month,object,0,0.00,12
5,arrival_date_week_number,int64,0,0.00,53
2,lead_time,int64,0,0.00,479
1,is_canceled,int64,0,0.00,2
7,stays_in_weekend_nights,int64,0,0.00,17
8,stays_in_week_nights,int64,0,0.00,35
10,children,float64,4,0.00,6
9,adults,int64,0,0.00,14
11,babies,int64,0,0.00,5
12,meal,object,0,0.00,5
6,arrival_date_day_of_month,int64,0,0.00,31
3,arrival_date_year,int64,0,0.00,3
15,distribution_channel,object,0,0.00,5
14,market_segment,object,0,0.00,8
18,previous_bookings_not_canceled,int64,0,0.00,73
16,is_repeated_guest,int64,0,0.00,2
19,reserved_room_type,object,0,0.00,10
20,assigned_room_type,object,0,0.00,12
21,booking_changes,int64,0,0.00,21
17,previous_cancellations,int64,0,0.00,15
22,deposit_type,object,0,0.00,3
25,days_in_waiting_list,int64,0,0.00,128
26,customer_type,object,0,0.00,4
27,adr,float64,0,0.00,8879
28,required_car_parking_spaces,int64,0,0.00,5
29,total_of_special_requests,int64,0,0.00,6
30,reservation_status,object,0,0.00,3
31,reservation_status_date,object,0,0.00,926

## 7. Missing Value Analysis

Missing values are examined at both the count and percentage
levels.

The treatment strategy is determined based on the meaning of
each variable rather than applying a single method to every
column.

In [24]:
missing_summary = pd.DataFrame({
    "Missing_Count": df.isna().sum(),
    "Missing_Percentage": (df.isna().mean() * 100).round(2)
})

missing_summary = missing_summary[
    missing_summary["Missing_Count"] > 0
].sort_values(
    by="Missing_Percentage",
    ascending=False
)

missing_summary

          Missing_Count  Missing_Percentage
company          112593               94.31
agent             16340               13.69
country             488                0.41
children              4                0.00

## 8. Duplicate Record Analysis

Duplicate records can introduce redundancy and may distort
downstream statistical analysis.

Exact duplicate rows are identified before any records are removed.
Only records that are identical across all available columns are
considered duplicates.

In [25]:
duplicate_count = df.duplicated().sum()

print(f"Number of exact duplicate rows: {duplicate_count:,}")

Number of exact duplicate rows: 31,994

In [26]:
duplicate_percentage = (
    duplicate_count / len(df) * 100
)

print(
    f"Percentage of exact duplicates: "
    f"{duplicate_percentage:.2f}%"
)

Percentage of exact duplicates: 26.80%

## 9. Data Type Validation

Data types are reviewed to ensure that numerical, categorical,
and date-related fields are represented appropriately.

Correct data types improve reliability during analysis and
prevent errors during downstream modeling.

In [27]:
dtype_summary = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.astype(str).values
})

dtype_summary

                            Column Data_Type
0                            hotel    object
1                      is_canceled     int64
2                        lead_time     int64
3                arrival_date_year     int64
4               arrival_date_month    object
5         arrival_date_week_number     int64
6        arrival_date_day_of_month     int64
7          stays_in_weekend_nights     int64
8             stays_in_week_nights     int64
9                           adults     int64
10                        children   float64
11                          babies     int64
12                            meal    object
13                         country    object
14                  market_segment    object
15            distribution_channel    object
16               is_repeated_guest     int64
17          previous_cancellations     int64
18  previous_bookings_not_canceled     int64
19              reserved_room_type    object
20              assigned_room_type    object
21                 booking_changes     int64
22                    deposit_type    object
23                           agent   float64
24                         company   float64
25            days_in_waiting_list     int64
26                   customer_type    object
27                             adr   float64
28     required_car_parking_spaces     int64
29       total_of_special_requests     int64
30              reservation_status    object
31         reservation_status_date    object

## 10. Categorical Value Validation

Categorical variables are examined for unexpected, inconsistent,
or potentially invalid values.

This step helps ensure that categories are represented consistently
before exploratory analysis and machine learning.

In [29]:
categorical_columns = df.select_dtypes(
    include="object"
).columns

for column in categorical_columns:
    print(f"\n{'='*60}")
    print(f"{column}")
    print(f"{'='*60}")
    print(df[column].value_counts(dropna=False).head(20))

============================================================
hotel
============================================================
hotel
City Hotel      79330
Resort Hotel    40060
Name: count, dtype: int64

============================================================
arrival_date_month
============================================================
arrival_date_month
August       13877
July         12661
May          11791
October      11160
April        11089
June         10939
September    10508
March         9794
February      8068
November      6794
December      6780
January       5929
Name: count, dtype: int64

============================================================
meal
============================================================
meal
BB           92310
HB           14463
SC           10650
Undefined     1169
FB             798
Name: count, dtype: int64

============================================================
country
============================================================
country
PRT    48590
GBR    12129
FRA    10415
ESP     8568
DEU     7287
ITA     3766
IRL     3375
BEL     2342
BRA     2224
NLD     2104
USA     2097
CHE     1730
CN      1279
AUT     1263
SWE     1024
CHN      999
POL      919
ISR      669
RUS      632
NOR      607
Name: count, dtype: int64

============================================================
market_segment
============================================================
market_segment
Online TA        56477
Offline TA/TO    24219
Groups           19811
Direct           12606
Corporate         5295
Complementary      743
Aviation           237
Undefined            2
Name: count, dtype: int64

============================================================
distribution_channel
============================================================
distribution_channel
TA/TO        97870
Direct       14645
Corporate     6677
GDS            193
Undefined        5
Name: count, dtype: int64

============================================================
reserved_room_type
============================================================
reserved_room_type
A    85994
D    19201
E     6535
F     2897
G     2094
B     1118
C      932
H      601
P       12
L        6
Name: count, dtype: int64

============================================================
assigned_room_type
============================================================
assigned_room_type
A    74053
D    25322
E     7806
F     3751
G     2553
C     2375
B     2163
H      712
I      363
K      279
P       12
L        1
Name: count, dtype: int64

============================================================
deposit_type
============================================================
deposit_type
No Deposit    104641
Non Refund     14587
Refundable       162
Name: count, dtype: int64

============================================================
customer_type
============================================================
customer_type
Transient          89613
Transient-Party    25124
Contract            4076
Group                577
Name: count, dtype: int64

============================================================
reservation_status
============================================================
reservation_status
Check-Out    75166
Canceled     43017
No-Show       1207
Name: count, dtype: int64

============================================================
reservation_status_date
============================================================
reservation_status_date
2015-10-21    1461
2015-07-06     805
2016-11-25     790
2015-01-01     763
2016-01-18     625
2015-07-02     469
2016-12-07     450
2015-12-18     423
2016-02-09     412
2016-04-04     382
2017-01-24     343
2016-11-21     340
2016-03-15     329
2017-01-19     321
2017-02-02     315
2016-09-20     303
2016-04-17     299
2017-05-05     297
2015-09-09     290
2016-04-27     283
Name: count, dtype: int64

## 11. Numerical Data Validation

Numerical variables are examined for unusual values,
unexpected ranges, and potential data-quality issues.

Outliers are not automatically removed because an extreme value
may represent a legitimate observation rather than an error.

In [30]:
numeric_columns = df.select_dtypes(
    include=np.number
).columns

numeric_summary = df[numeric_columns].describe().T

numeric_summary

,count,mean,std,min,25%,50%,75%,max
is_canceled,119390.0,0.370416,0.482918,0.00,0.00,0.000,1.0,1.0
lead_time,119390.0,104.011416,106.863097,0.00,18.00,69.000,160.0,737.0
arrival_date_year,119390.0,2016.156554,0.707476,2015.00,2016.00,2016.000,2017.0,2017.0
arrival_date_week_number,119390.0,27.165173,13.605138,1.00,16.00,28.000,38.0,53.0
arrival_date_day_of_month,119390.0,15.798241,8.780829,1.00,8.00,16.000,23.0,31.0
stays_in_weekend_nights,119390.0,0.927599,0.998613,0.00,0.00,1.000,2.0,19.0
stays_in_week_nights,119390.0,2.500302,1.908286,0.00,1.00,2.000,3.0,50.0
adults,119390.0,1.856403,0.579261,0.00,2.00,2.000,2.0,55.0
children,119386.0,0.103890,0.398561,0.00,0.00,0.000,0.0,10.0
babies,119390.0,0.007949,0.097436,0.00,0.00,0.000,0.0,10.0
is_repeated_guest,119390.0,0.031912,0.175767,0.00,0.00,0.000,0.0,1.0
previous_cancellations,119390.0,0.087118,0.844336,0.00,0.00,0.000,0.0,26.0
previous_bookings_not_canceled,119390.0,0.137097,1.497437,0.00,0.00,0.000,0.0,72.0
booking_changes,119390.0,0.221124,0.652306,0.00,0.00,0.000,0.0,21.0
agent,103050.0,86.693382,110.774548,1.00,9.00,14.000,229.0,535.0
company,6797.0,189.266735,131.655015,6.00,62.00,179.000,270.0,543.0
days_in_waiting_list,119390.0,2.321149,17.594721,0.00,0.00,0.000,0.0,391.0
adr,119390.0,101.831122,50.535790,-6.38,69.29,94.575,126.0,5400.0
required_car_parking_spaces,119390.0,0.062518,0.245291,0.00,0.00,0.000,0.0,8.0
total_of_special_requests,119390.0,0.571363,0.792798,0.00,0.00,0.000,1.0,5.0

In [31]:
df["adults"].value_counts().sort_index()

adults
0       403
1     23027
2     89680
3      6202
4        62
5         2
6         1
10        1
20        2
26        5
27        2
40        1
50        1
55        1
Name: count, dtype: int64

In [33]:
df["children"].value_counts(dropna=False).sort_index()

children
0.0     110796
1.0       4861
2.0       3652
3.0         76
10.0         1
NaN          4
Name: count, dtype: int64

In [34]:
df["babies"].value_counts().sort_index()

babies
0     118473
1        900
2         15
9          1
10         1
Name: count, dtype: int64

In [36]:
df["adr"].describe()

count    119390.000000
mean        101.831122
std          50.535790
min          -6.380000
25%          69.290000
50%          94.575000
75%         126.000000
max        5400.000000
Name: adr, dtype: float64

In [37]:
df[df["adr"] < 0][
    ["hotel", "adults", "children", "babies", "adr"]
]

              hotel  adults  children  babies   adr
14969  Resort Hotel       2       0.0       0 -6.38

## 12. Date Preparation

The arrival date is represented across separate year, month,
and day columns.

A single datetime field is created to simplify chronological
analysis and downstream feature engineering.

The original date components are retained to preserve the
original information.

In [38]:
month_mapping = {
    "January": 1,
    "February": 2,
    "March": 3,
    "April": 4,
    "May": 5,
    "June": 6,
    "July": 7,
    "August": 8,
    "September": 9,
    "October": 10,
    "November": 11,
    "December": 12
}

df["arrival_month_num"] = (
    df["arrival_date_month"].map(month_mapping)
)

In [39]:
df["arrival_date"] = pd.to_datetime(
    {
        "year": df["arrival_date_year"],
        "month": df["arrival_month_num"],
        "day": df["arrival_date_day_of_month"]
    },
    errors="coerce"
)

In [40]:
df[
    [
        "arrival_date_year",
        "arrival_date_month",
        "arrival_date_day_of_month",
        "arrival_date"
    ]
].head(10)

,arrival_date_year,arrival_date_month,arrival_date_day_of_month,arrival_date
0,2015,July,1,2015-07-01
1,2015,July,1,2015-07-01
2,2015,July,1,2015-07-01
3,2015,July,1,2015-07-01
4,2015,July,1,2015-07-01
5,2015,July,1,2015-07-01
6,2015,July,1,2015-07-01
7,2015,July,1,2015-07-01
8,2015,July,1,2015-07-01
9,2015,July,1,2015-07-01

## 13. Reservation Status Date Conversion

The reservation status date is currently stored as text.
It is converted into a datetime format to support chronological
analysis and validation.

In [41]:
df["reservation_status_date"] = pd.to_datetime(
    df["reservation_status_date"],
    errors="coerce"
)

df["reservation_status_date"].dtype

dtype('<M8[ns]')

## 14. Missing Value Treatment

Missing values are handled according to the meaning and role
of each variable.

The following assumptions are applied:

- `company`: Missing values indicate that no company information
  was associated with the booking. They are labeled as
  `Not Specified`.

- `agent`: Missing values indicate that an agent was not recorded.
  They are labeled as `Not Specified`.

- `country`: Missing values indicate that the country of origin
  was not available. They are labeled as `Unknown`.

- `children`: Only a very small number of records contain missing
  values. These values are replaced with 0 because the variable
  represents the number of children associated with the booking,
  and no child count was recorded for these observations.

These transformations preserve the records while making missing
information explicit.

In [43]:
df["company"] = df["company"].fillna("Not Specified")
df["agent"] = df["agent"].fillna("Not Specified")
df["country"] = df["country"].fillna("Unknown")
df["children"] = df["children"].fillna(0)

In [44]:
df.isna().sum().sort_values(ascending=False).head(10)

hotel                        0
is_canceled                  0
lead_time                    0
arrival_date_year            0
arrival_date_month           0
arrival_date_week_number     0
arrival_date_day_of_month    0
stays_in_weekend_nights      0
stays_in_week_nights         0
adults                       0
dtype: int64

## 15. Duplicate Removal

Exact duplicate records are removed from the working dataset.

Only rows that are identical across all available columns are
removed. Records that differ in at least one attribute are retained.

This approach avoids removing potentially valid bookings merely
because they share some characteristics with another booking.

In [45]:
rows_before_duplicates = len(df)

df = df.drop_duplicates().copy()

rows_after_duplicates = len(df)

duplicates_removed = (
    rows_before_duplicates - rows_after_duplicates
)

print(f"Rows before duplicate removal: {rows_before_duplicates:,}")
print(f"Duplicate rows removed: {duplicates_removed:,}")
print(f"Rows after duplicate removal: {rows_after_duplicates:,}")

Rows before duplicate removal: 119,390
Duplicate rows removed: 31,994
Rows after duplicate removal: 87,396

## 16. Handling Invalid ADR Values

The `adr` variable represents the average daily rate.

A negative ADR is not logically valid because a room rate cannot
be negative.

The dataset contains a negative ADR observation. Since this value
cannot represent a valid room rate, it is treated as missing
rather than assigning an arbitrary replacement value.

The value will therefore be imputed using the median ADR during
the preparation stage.

In [47]:
df[df["adr"] < 0][
    ["hotel", "adr", "is_canceled", "reservation_status"]
]

              hotel   adr  is_canceled reservation_status
14969  Resort Hotel -6.38            0          Check-Out

In [48]:
negative_adr_count = (df["adr"] < 0).sum()

print(
    f"Negative ADR records identified: {negative_adr_count}"
)

Negative ADR records identified: 1

In [49]:
df.loc[df["adr"] < 0, "adr"] = np.nan

In [50]:
median_adr = df["adr"].median()

df["adr"] = df["adr"].fillna(median_adr)

In [51]:
print("Negative ADR values remaining:", (df["adr"] < 0).sum())
print("Missing ADR values remaining:", df["adr"].isna().sum())

Negative ADR values remaining: 0
Missing ADR values remaining: 0

## 17. Feature Engineering

A small number of derived variables are created to improve the
usability of the prepared dataset.

The engineered features represent meaningful booking-level
information and will also support subsequent exploratory
analysis and machine learning tasks.

In [53]:
df["total_stay_nights"] = (
    df["stays_in_weekend_nights"]
    + df["stays_in_week_nights"]
)

In [54]:
df["total_guests"] = (
    df["adults"]
    + df["children"]
    + df["babies"]
)

In [55]:
df[
    [
        "stays_in_weekend_nights",
        "stays_in_week_nights",
        "total_stay_nights",
        "adults",
        "children",
        "babies",
        "total_guests"
    ]
].head()

,stays_in_weekend_nights,stays_in_week_nights,total_stay_nights,adults,children,babies,total_guests
0,0,0,0,2,0.0,0,2.0
1,0,0,0,2,0.0,0,2.0
2,0,1,1,1,0.0,0,1.0
3,0,1,1,1,0.0,0,1.0
4,0,2,2,2,0.0,0,2.0

## 18. Final Data Validation

After completing the preparation steps, the dataset is
re-evaluated to confirm that the intended transformations
were successful.

The final validation checks:

- Dataset dimensions
- Missing values
- Duplicate records
- Data types
- Invalid ADR values
- Date conversion
- Newly created features

In [56]:
print("Final dataset shape:", df.shape)

Final dataset shape: (87396, 36)

In [57]:
print("\nMissing values:")
print(df.isna().sum().sort_values(ascending=False).head(10))

Missing values:
hotel                        0
is_canceled                  0
lead_time                    0
arrival_date_year            0
arrival_date_month           0
arrival_date_week_number     0
arrival_date_day_of_month    0
stays_in_weekend_nights      0
stays_in_week_nights         0
adults                       0
dtype: int64

In [58]:
print(
    "\nDuplicate rows:",
    df.duplicated().sum()
)

Duplicate rows: 0

In [59]:
print(
    "\nNegative ADR values:",
    (df["adr"] < 0).sum()
)

Negative ADR values: 0

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87396 entries, 0 to 119389
Data columns (total 36 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87396 non-null  object
 1   is_canceled                     87396 non-null  int64
 2   lead_time                       87396 non-null  int64
 3   arrival_date_year               87396 non-null  int64
 4   arrival_date_month              87396 non-null  object
 5   arrival_date_week_number        87396 non-null  int64
 6   arrival_date_day_of_month       87396 non-null  int64
 7   stays_in_weekend_nights         87396 non-null  int64
 8   stays_in_week_nights            87396 non-null  int64
 9   adults                          87396 non-null  int64
 10  children                        87396 non-null  float64
 11  babies                          87396 non-null  int64
 12  meal                            87396 non-null  object
 13  country                         87396 non-null  object
 14  market_segment                  87396 non-null  object
 15  distribution_channel            87396 non-null  object
 16  is_repeated_guest               87396 non-null  int64
 17  previous_cancellations          87396 non-null  int64
 18  previous_bookings_not_canceled  87396 non-null  int64
 19  reserved_room_type              87396 non-null  object
 20  assigned_room_type              87396 non-null  object
 21  booking_changes                 87396 non-null  int64
 22  deposit_type                    87396 non-null  object
 23  agent                           87396 non-null  object
 24  company                         87396 non-null  object
 25  days_in_waiting_list            87396 non-null  int64
 26  customer_type                   87396 non-null  object
 27  adr                             87396 non-null  float64
 28  required_car_parking_spaces     87396 non-null  int64
 29  total_of_special_requests       87396 non-null  int64
 30  reservation_status              87396 non-null  object
 31  reservation_status_date         87396 non-null  datetime64[ns]
 32  arrival_month_num               87396 non-null  int64
 33  arrival_date                    87396 non-null  datetime64[ns]
 34  total_stay_nights               87396 non-null  int64
 35  total_guests                    87396 non-null  float64
dtypes: datetime64[ns](2), float64(3), int64(18), object(13)
memory usage: 24.7+ MB

## 19. Before vs After Data Preparation

The following summary compares the original dataset with the
prepared dataset.

This provides a transparent view of the impact of the data
preparation process.

In [61]:
summary = pd.DataFrame({
    "Metric": [
        "Number of Rows",
        "Number of Columns",
        "Missing Value Cells",
        "Duplicate Rows"
    ],
    "Before Preparation": [
        len(df_raw),
        df_raw.shape[1],
        df_raw.isna().sum().sum(),
        df_raw.duplicated().sum()
    ],
    "After Preparation": [
        len(df),
        df.shape[1],
        df.isna().sum().sum(),
        df.duplicated().sum()
    ]
})

summary

                Metric  Before Preparation  After Preparation
0       Number of Rows              119390              87396
1    Number of Columns                  32                 36
2  Missing Value Cells              129425                  0
3       Duplicate Rows               31994                  0

## 20. Export Prepared Dataset

The final prepared dataset is exported as a CSV file.

The original raw dataset is preserved separately, while the
prepared dataset contains the documented cleaning and
feature-engineering transformations.

In [64]:
df.to_csv(
    "hotel_bookings_cleaned.csv",
    index=False
)

print("Prepared dataset exported successfully.")

Prepared dataset exported successfully.

## 21. Key Takeaways

The data preparation process established a reliable foundation
for subsequent data science tasks.

### Key actions completed

- Inspected the structure and quality of the dataset
- Identified and treated missing values according to variable meaning
- Removed exact duplicate records
- Validated numerical ranges and identified invalid ADR values
- Converted date-related fields to appropriate datetime formats
- Created an arrival date feature
- Created total stay and total guest features
- Performed final data-quality validation
- Exported the prepared dataset for downstream analysis

### Preparation Principle

Data cleaning decisions were based on the meaning and context
of each variable rather than applying a uniform transformation
to all columns.